apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-springboot
  template:
    metadata:
      labels:
        app: java-springboot
    spec:
      containers:
        - name: springboot
          image: pavanreddy560/sampledemo1:docker-demo1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: java-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: java-springboot
